services:
  - type: web
    name: tvarit-demo
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: demo
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
